name: ETCalc WordPress CI

on: [push, pull_request]

jobs:
  verify_ubuntu:
    name: Verify syntax on latest Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: pecl
          extensions: swoole
      - name: Verify
        uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: './/etcalc-wordpress-plugin'
